### ISSUE TITLE
[TBC] ERROR:SpellAuraHolder

### ISSUE THREAD

**Issue by gpcore** [cmangos/issues#1128]
**Current behavior**: 
Find in logs many times:
2016-10-19 22:01:11 ERROR:SpellAuraHolder (Spell 2383) is in process but attempt removed at SpellAuraHolder (Spell 2383) adding, need add stack rule for Unit::RemoveNoStackAurasDueToAuraHolder

2016-10-19 21:26:13 ERROR:SpellAuraHolder (Spell 2580) is in process but attempt removed at SpellAuraHolder (Spell 2580) adding, need add stack rule for Unit::RemoveNoStackAurasDueToAuraHolder

2016-10-19 21:26:15 ERROR:SpellAuraHolder (Spell 19883) is in process but attempt removed at SpellAuraHolder (Spell 19883) adding, need add stack rule for Unit::RemoveNoStackAurasDueToAuraHolder

**Client version**: 
2.4.3
**Commit hash**: 
https://github.com/cmangos/mangos-tbc/commit/e1608b3f2a82601d4f98417701a757bd97088dab
**Database version**: 
tbc 1.5.0
**Operating system**: 
linux openSuse 42.1

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Warlockbugs** [comment]
It was already fixed in https://github.com/cmangos/mangos-tbc/commit/caf4d9957e4d9258c3d82f437e46556b8881d3b9.

**Comment by Fabi** [comment]
As I said.... @gpcore, please start using the latest version of the core. Your commit hash is still the same...

**Comment by gpcore** [comment]
I do Fabi now! :)
