### ISSUE TITLE
Classic - Raid - Saving

### ISSUE THREAD

**Issue by dazidkk** [cmangos/issues#1298]
Raid Saving is broken atm due to the recent commit https://github.com/cmangos/mangos-classic/commit/ce0ed616ebe104359b84eed0f10e969ceea1ca4d 

If you do a raid and kill a boss getting the saved status, proceeding to logout after leaving the raid group the saved status will disapear. Probaly other similar issues aswell.

**Comment by wowmui** [comment]
fixed by https://github.com/cmangos/mangos-classic/commit/e947d98a39bc0849b25f076ea6c9756965c29ccc

**Comment by dazidkk** [comment]
Didnt fix it. And aint that commit already applied to the core?

**Comment by wowmui** [comment]
ALTER TABLE character_db_version CHANGE COLUMN required_z2686_01_characters_reset_talents required_z2694_01_characters_instance bit;

ALTER TABLE instance ADD COLUMN `encountersMask` int(10) unsigned NOT NULL DEFAULT '0' AFTER resettime;
 After applyed this SQL. And yes, that commit already applied to the core.
 I tested. no problem now.
