### ISSUE TITLE
[CLASSIC] Summoned Pets/Minions That are Summoned by Creatures Follow You Forever

### ISSUE THREAD

**Issue by Razfury** [cmangos/issues#1385]
**Current behavior**: 
Minions or Pets summoned by NPCs are bugged, if you run out of range the NPC goes back to its spawn point HOWEVER the minion/pet does not and continues to follow you forever.
**Expected behavior**: 
The minion/pet should go back to master whenever it goes out of its threat radius
**Steps to reproduce**:

1. Go to Stormgarde Keep and find a hostile NPC with a voidwalker
2.  Aggro the caster & voidwalker run away until the NPC runs back
3.  Watch the voidwalker chase you endlessly & not return to the master

**Client version**: 
1.12.1
**Commit hash**: 
https://github.com/cmangos/mangos-classic/commit/b44b2a95a6525ce66ba52ffabc0b96e377e5d733
**Database version**: 
current
**Operating system**: 
Win 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
Linked to leash and summons not having homeposition.

**Comment by AnonXS** [comment]
Can someone check if this is resolved, e.g check warlocks in tanaris or the treant guys in stonetalon mountains.

**Comment by Phatcat** [comment]
This has been resolved, yes, there is however another issue with creature's pet's on evade, they don't stay in actual evade mode when their master evades, so as soon as they lose aggro on you and start running home, you can intercept them and re-engage the pet and force the evading master back into combat with you, but that is sort of a different issue.

**Comment by RussianE39** [comment]
I think it's actually not resolved still, just checked latest cmangos-tbc with latest DB. The 7 dwarves encounter in BRD ends up with Doom'rel summoned warlocks which follow player while not doing any damage.

**Comment by Phatcat** [comment]
I can see this still being an issue in instances where mobs don't evade unless you're unreachable, so that carries over to their summons as well. Perhaps that's intended. Maybe guardians in instances need to be researched a bit. Them following without doing any damage sounds like another issue, though. Are they supposed to damage the player? Supposed to despawn? What's supposed to happen exactly? Do you have video of the encounter from retail?

**Comment by RussianE39** [comment]
https://youtu.be/0F0Xz_NKCp8?t=163

**Comment by Phatcat** [comment]
So they should stay hostile (they should never evade as they are in an instance, unless whole team dies or breaks combat by vanish/feign death)

So the problem isn't that they are following the player, the problem is that they stop doing damage.
Do they do damage before their summoner dies currently?

**Comment by RussianE39** [comment]
The only thing they do after Doom'rel summon them - following player, until player moves to max chase range. They should attack player at least.

**Comment by AnonXS** [comment]
Doom'rel issue is that the unitflags removal is not inherited by his GuardianAI Spawns entry: 8996 - dbunitflags = 0

**Comment by al3xc1985** [comment]
@killerwife wasn't this refactored by warlockbugs?

**Comment by killerwife** [comment]
Pet now evades synchronously with owner. Fixed by leashing rework.
