### ISSUE TITLE
[classic] Hallow's End - Apple Bob

### ISSUE THREAD

**Issue by RichardGe** [cmangos/issues#1496]
First of all, my database is several months old - but I don't think it has been fixed - my bad if issue is already solved.

when I right click on Hallow's End Apple Bob (object=180523) , nothing happens

in order to solve that, you have to set :  
`
UPDATE gameobject_template SET data0 = CASE 
WHEN Name = 'Apple Bob' 
THEN '57'  
ELSE data0
END
`
(57 is the lock ID for classic chest)

( issue related to https://github.com/cmangos/issues/issues/477 )

also note that the Bobbing Apple (item=20516) are not giving the "Stamina and Spirit for 15 min". but there is a ticket for that already : https://github.com/cmangos/issues/issues/19

**Comment by RichardGe** [comment]
solved in classic-db/commit/a6475972529aef93d8877f2f03550d26e4ec2df0

**Comment by linuxpng** [comment]
I just pulled and applied the latest DBs, this is still not working for me.
DB Hash:
$ git rev-parse HEAD
846bb2b754d6d91ccb968a6e156a4c9a00ccd9e0

Mangos Hash:
$ git rev-parse HEAD
fa55bf677e7df1e8af1d1218c625a530b9507687

**Comment by cala** [comment]
Did you delete your WDB files ?

**Comment by linuxpng** [comment]
I hadn't prior, but I just did and I have the same result.  

(sidenote)Wasn't this event supposed to have quests from the pumpkins, by the innkeepers, for the wands as well?

**Comment by RichardGe** [comment]
@linuxpng 
do you mean that you don't even have the progress bar ?
![image](https://user-images.githubusercontent.com/2279126/32021449-b08e4cc6-b9d3-11e7-96f2-6dddf8c6d8cd.png)
but you have at least the gear mouse cursor don't you?
are you on Classic ?
on my side I confirm changing data0 to 57 solved the issue.

**Comment by linuxpng** [comment]
I apologize. I tried this on my mac and sure enough, it works fine.  I have both the live WoW client and the 1.12 WoW client running in wine on linux.  I cleared the wrong cache X(
