### ISSUE TITLE
[TBC]Pet Trainer doesn't teach pet spells - just takes gold

### ISSUE THREAD

**Issue by yatzi888** [cmangos/issues#1827]
**Current behavior**: When trying to upgrade pet abilities at the pet trainer, nothing happens when pressing train. It just takes the gold.

**Expected behavior**: Should learn the spell and put it into players beast training

**Steps to reproduce**:

1. tame pet
2. go to pet trainer
3. try to learn spell 

Video - (please note I changed the spell trainer to cost no gold per skills. at the normal trainer it just takes the gold) This seemed to crop up from the recent overhaul of the skill learning. Going back to a core dated on the 12th of December 2018 caused the problem to go away.

https://youtu.be/37I130dvVIs?t=23

**Client version**: 2.4.3

**Commit hash**: 
1023ec72db753ebf6d969ba67a5d7659ab65230d

**Database version**: 
latest

**Operating system**: 
Windows Server 2012

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Warlockbugs** [comment]
The actual training works, pet receives new spells. It is a problem with trainer's list display after training, listing already known spells, allowing to request a training and charging for it over and over for no practical effect other than burning gold.

**Comment by Warlockbugs** [comment]
This issue is fixed by:
https://github.com/cmangos/mangos-tbc/commit/79c8f0a4185af4d36bd693ef58a87605503fcf61
https://github.com/cmangos/mangos-tbc/commit/60b684590f6cd1d4aedd453793f3d259943b2371

**Comment by yatzi888** [comment]
@Warlockbugs Sorry if I'm being silly but I downloaded the lastest core and I'm still experiencing the same issue. Has the change not been compiled yet? Not sure how to accurately test.

**Comment by Warlockbugs** [comment]
Pushed another patch today.

**Comment by yatzi888** [comment]
@Warlockbugs awesome! Thanks

**Comment by yatzi888** [comment]
@Warlockbugs tested and working! 👯‍♂️
