### ISSUE TITLE
🐛 [Bug Report] Deeprun Tram not working

### ISSUE THREAD

**Issue by kelbren** [cmangos/issues#2339]
## 🐛 Bugreport
As of TBC patches on December 8th Deeprun Tram does not show up. No train comes into the station.

### Expected behavior
Train should work and travel to Ironforge.

### Version & Environment
  Client Version - "2.4.3" (TBC)
  
  Operating System 
  - Linux Ubuntu 18.04r

### Steps to reproduce
1. clean pull and build
2. Enter into Deeprun Tram station.. wait for train.
3. No train shows up.

**Comment by killerwife** [comment]
https://github.com/cmangos/tbc-db/commit/70ed4d30cd7b574ec53bcfba8f73bbbf25a5412f should fix it.

**Comment by kelbren** [comment]
I updated with latest pull and rebuilt server, I even re-extracted all maps etc.  I waited for 20 minutes and no train came.  One time I entered the instance from Ironforge, the train showed up, I stepped onto it, the train vanished. and I fell to the floor.  after that it never showed up again.

**Comment by Muehe** [comment]
Can confirm, still an issue as of 9fafcdc414609cc74c891dd0d7de16c0a9336668.

Entered on Stormwind side, waited for some time. No train. Ran over to Ironforge with `.mod aspeed 8`. Saw the train leaving the station but not all carts. Was able to track it for some time, saw another cart disappearing, lost the last one. Not seen a train for a few minutes. Went back to Ironforge, single cart arrives on the track I just ran along. Been sitting in that cart for a few rotations now, but something is definitely off with the spawning.

**Comment by kelbren** [comment]
Tested in latest pull from the WotLK branch. rebuild of everything, including extracted maps etc.  has the same issue.

**Comment by kelbren** [comment]
As of cmangos/mangos-tbc@ 29ec5b4   Deeprun Tram train cars now show up, but if you walk on the car when its moving it will disappear and you fall to the ground.  Had some strange issues with the great lift in thousand needles as well, when walking off the lift at the top or bottom it would vanish.... and then flicker.. as I walked away.  then suddenly re-appear.  Pets will sometimes fall to the ground and disappear as well while the car is moving.

**Comment by killerwife** [comment]
I am working on it. Resolving several transport issues at once. I have one commit ready in the pipeline which I deployed to live realm and if it resolves the problems, it will be pushed to cmangos. ETA very soon

**Comment by kelbren** [comment]
Love al lthe work so far. Pets board the cars fine, then dissapear and/or fall. latest updates still having some strange issues with train cars.  if you do not move on the car once its in motion it takes you to the destination. but if you move at all when the car drops down on the z axis you fall off and the car disappears.. never to return.  
I will keep testing.  Thanks for all the amazing work.

**Comment by killerwife** [comment]
I pushed recently this https://github.com/cmangos/tbc-db/commit/c59abc4e89c6b51bf649241014b78cb816e4f539 did you guys try that?

**Comment by Muehe** [comment]
When I retested yesterday this commit was already included, but the problem was still there. Didn't include the latest core changes discussed in #198 though.

By the way, I have pretty consistently only one cart on the track closer to the entrance and three carts on the track further from the entrance. That is when there are any carts at all, can still stand in a station for minutes at a time without anything happening, especially after falling through a transport.

Another weird thing happened when I deliberately jumped off, still heard the tram sounds at the point where I landed for some time.

**Comment by Muehe** [comment]
Correction. Depends on where you start.

When you start server and login on Stormwind side no train appears. When you then run towards Ironforge you get one cart on track 1 and through some unknown steps three carts on track 2.

When you start server and login with character on Ironforge side you see three carts on track one immediately leave and then return later, no activity on track 2. Entering the carts on track 1 and driving was ok, leaving them on Stormwind side made them disappear, but made three carts spawn on track 2 and immediately leave.

Seems like the "always active" change didn't work?

Generally entering and leaving the carts, even when they stand, seems to make themselves and/or other carts randomly (dis-)appear. Not always though.

And the "disappearing when moving while transport z changes" is also still present as of latest commits.

**Comment by killerwife** [comment]
Found the issues and solutions. Its composed of two issues, we dont autoload go actives atm and the dbc is different from wotlk, where i was doing most recent work. Will push fix within the hour.

**Comment by killerwife** [comment]
3 separate issues -
https://github.com/cmangos/mangos-tbc/commit/21026b56013de7771ff88523cfce484b5af0edd0
https://github.com/cmangos/mangos-tbc/commit/a70612d429d3c64bcb9d758d4b7edeb6de28f659
https://github.com/cmangos/tbc-db/commit/c8ddacb24344cddc0405946aa079bd59d5bc92dd

**Comment by Muehe** [comment]
This seems to have fixed all the issues, no problems anymore with entering/exiting, spawning, or z-value change. Haven't tested pets though.

@kelbren Please retest. I'll close the issue for now, but feel free to post here if you find anymore problems.

**Comment by kelbren** [comment]
Tested for TBC branch. Amazing work. Tram work perfect. ships too. Thanks everyone.
