### ISSUE TITLE
🐛 [Bug Report] Mage: Improved Blizzard is not working

### ISSUE THREAD

**Issue by Oldsalt0** [cmangos/issues#3032]
### Bug Details

Improved Blizzard talent currently doesn't add a "Chilled" effect on its damaged targets whether we have 1, 2 or 3 points on that talent.   

![image](https://user-images.githubusercontent.com/20860048/174738418-a33316d8-3ad4-4261-a638-011046e3afa9.png)

### Steps to Reproduce

1. Put talent points into Improved Blizzard (from 1 to 3)
2. Cast Blizzard (any rank) to an enemy target

### Expected behavior

The Chilled effect should be applied when Blizzard damages an enemy if you have Improved Blizzard.

There are 3 Chilled spells, they depend on your number of points into Improved Blizzard:
- 1 point (30% slow): Spell ID 12484
- 2 points (50% slow): Spell ID 12485
- 3 points (65% slow): Spell ID 12486

**Side note:** This Chilled effect's duration should be increased by the Permafrost talent (+1 second for each point) and should have a 5/10/15% chance to proc Frostbite. Exactly the same way it currently does with the slowing component of Frostbolt.
![image](https://user-images.githubusercontent.com/20860048/174740658-d5756a8e-fdb6-4898-acba-69664151bd1b.png)
![image](https://user-images.githubusercontent.com/20860048/174743735-e859280f-fc01-4752-8046-98ab8549d139.png)

### Core SHA1 Commit Hash

d1ec084fc94a9e06c7460e126d248e690c809cb1

### Database SHA1 Commit Hash

7edee7cd5e0df4a68cd7fecdca7c9eec3ca825d5

### Operating System

Linux (Ubuntu 20.04 LTS)

### Client Version

2.4.3 (The Burning Crusade)

**Comment by danjohnso** [comment]
Additional info: In Wrath, Chilled to the Bone is not applying its slow either

**Comment by killerwife** [comment]
Fixed on wotlk, will port to tbc later. First i want to make a round of issue fixes before i propagate it.

**Comment by danjohnso** [comment]
@killerwife the chill effect is still not being applied from Blizzard, other spells seem to be working with permafrost though

**Comment by killerwife** [comment]
Did you reapply db?

**Comment by danjohnso** [comment]
Guess not, sorry, looks good now.
