### ISSUE TITLE
🐛 [Bug Report] [TBC] Investigate the Blue Recluse (1920) cannot be completed

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#3218]
### Bug Details

1. Rift Spawn always appears.
2. Rift Spawn cannot catch by Chest of Containment Coffers

### Steps to Reproduce

1. go cr id 5497
2. accept the quest and get the Cantation of Manifestation & Chest of Containment Coffers
3. .go xyz -9064.388 829.88 108.418 0
4. kill Rift Spawn and use Chest of Containment Coffers

### Core SHA1 Commit Hash

01b98b1fa68016b7c68de3c998aebbfe1d154940

### Database SHA1 Commit Hash

96b94fbb54b12b642a5de569e45014caf91b578e

### Operating System

Ubuntu

### Client Version

2.4.3 (The Burning Crusade)

**Comment by aleigood** [comment]
This is a TBC problem, but the problem has not been solved in TBC 🤣

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/203588164-acfbdc4a-450e-4777-a0f0-67c0ebea2954.png)

with this quest the "chaining of quests" might be smoother, but it does not fix any issue in regards with this mob in tbc core, he becomes interactable has correct npcflags but you click him an dnothing happens.

cpp is identical for both mobs in tbc and wotlk, if you kill and force respawn him he will respawn at this location instead of original spawn location, he will set orientation towards you but is not effectivly interactable.

when you restart the server, he will respawn at his original spawn location, and will be interactable.

![grafik](https://user-images.githubusercontent.com/19734826/203588760-ad7ff753-d2bb-4f7f-a1eb-a61641988467.png)

not a db issue but strange issue regarding his core script or some general behavior in tbcmangos vs wotlkmangos. @killerwife
