### ISSUE TITLE
🐛 [Bug Report] [WoTLK] Server crash upon startup

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#3416]
### Bug Details

With in a few seconds after "mangosd" is finished initializing, it crashes with no indication why.

I was still working on the memory leak issue, and had perform a core update yesterday 5/20/2023 ~8:00am EST. I compiled it and got one new warning (maybe unrelated). https://github.com/cmangos/issues/issues/3415.

Installed and started sever with this mangosd configuration
```
UseProcessors = 0
ProcessPriority = 1
Compression = 1
PlayerLimit = 100
SaveRespawnTimeImmediately = 1
MaxOverspeedPings = 2
GridUnload = 0
LoadAllGridsOnMaps = ""
Autoload.Active = 1
GridCleanUpDelay = 300000
MapUpdateInterval = 100
ChangeWeatherInterval = 600000
PlayerSave.Interval = 300000
PlayerSave.Stats.MinLevel = 0
PlayerSave.Stats.SaveOnlyOnLogout = 1
vmap.enableLOS = 1
vmap.enableHeight = 1
vmap.enableIndoorCheck = 1
DetectPosCollision = 1
mmap.enabled = 1
mmap.ignoreMapIds = ""
PathFinder.OptimizePath = 1
PathFinder.NormalizeZ = 1
UpdateUptimeInterval = 10
MapUpdate.Threads = 4
MaxCoreStuckTime = 0
AddonChannel = 1
CleanCharacterDB = 1
MaxWhoListReturns = 49
```
The server crashed after it was finished initializing. Tried five other times. Only variation that i could find was large differences in  startup times ... ranging from 1 minute and 11 seconds to 1 minute and 57 seconds. My normal is ~ 1 minute 45 seconds plus or minus 5 or so seconds
I then changed mangosd configuration to;
```
GridUnload = 1
Autoload.Active = 0
```
Server finished initializing in 1 minute and 8 seconds, and has stayed up and running so far. I am going to leave it running for a while to make sure that it will stay up, then play with both those parameters to narrow down which is the cause.

### Steps to Reproduce

1.Start latest WoTLK core
2.
3.
4.

### Core SHA1 Commit Hash

f7aec4af7c95914227d8fa7888379e5240e5c1fc

### Database SHA1 Commit Hash

97899e61c8c33559da6183b46de5a4409c2f2c07

### Operating System

Ubuntu 20.04 LTS Server, Ubuntu 20.04 LTS Desktop Client

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by adellaci** [comment]
So far server has not crash. I will change the parameters tomorrow to see which one is the issue.

**Comment by adellaci** [comment]
It crash right after completing initialization when i set
```
Autoload.Active = 1
```

**Comment by evil-at-wow** [comment]
I had a similar issue like three weeks ago in my TBC core (the core crashing like instantly after it brought the server up, also having also with Autoload.Active = 1 in my config), and that was because of cmangos/mangos-wotlk@e7874b39fa578a5ae99d7a0de4d496398026928a (if my memory serves me well, there was some group of creatures being marked as active that is using a condition based on world state, and that caused nasty things as mentioned in the commit). It's hard to say if you run into the same issue without a call stack, so I'm just doing an educated guess here based on symptoms and provided observations.

Based on the core SHA1 you mention here, that fix is not in your core, so that could explain the crash. On the other hand, you mentioned that you updated your core on 5/20/2023 ~8:00am EST, and at that point the referenced fix was already in the repository... so could it be you copy/pasted a wrong hash or perhaps didn't update the core to the latest commit at the time?

In case it was not the latest commit at the time, note that having a core with cmangos/mangos-wotlk@6c6a48e3aa1f2e147f28ab03c34bb58887a73627 included - in case you don't really fancy grabbing the very latest commit - basically gives you like two dozen crash and memory leak fixes that have been around in TBC for months and that I finally merged to the Wrath core like two weeks ago. I'm obviously not saying you have to include these - you could just forward a bit to include cmangos/mangos-wotlk@e7874b39fa578a5ae99d7a0de4d496398026928a - but I wanted to point them out so you're aware.

**Comment by adellaci** [comment]
I will double check the hash tonight

May 24, 2023 17:55:57 evil-at-wow ***@***.***>:

**Comment by adellaci** [comment]
@evil-at-wow 
So i am running (Using commit hash(f7aec4af7c95914227d8fa7888379e5240e5c1fc) committed on 2023-04-15T00:39:20+02:00)
I will run a pull now and recompile

**Comment by adellaci** [comment]
@evil-at-wow 
i am run 'Using commit hash(219be0df551e7fde494819ca785bcfe306510e30) committed on 2023-05-31T18:33:40+02:00' now and the server still crashes right after World Initialization is complete when i have  'AutoLoad.Active = 1'

Any suggestion on going about troubleshooting?

**Comment by evil-at-wow** [comment]
I can't quickly check myself if I can reproduce this because I don't have a Wrath core set up, but I would suggest the following:

* Create a debug build of the core for once (build the core the same as you usually do, but add '-DDEBUG=1' to the CMake command line). That should give us a useful stack trace later with readable function names. Everything else can remain exactly the same (database, config, etc).
* Then use this debug build of mangosd to see if you can reproduce the crash. Initially just run it once and see if it sitll crashes. If that's the case, as we expect, then we want to get a stack trace to understand what the core was doing at that point.
* I think the easiest way to get a stack trace is probably to run the debug build of mangosd in gdb (a debugger) <sup>(1)</sup>. You'll have to install gdb first if you don't have it installed already, but going via core dumps will eventually also require gdb. With gdb installed, you can run ```gdb /path/to/mangosd``` from the same directory where you normally start it from, and then once gdb has loaded the binary, type 'r [arguments]` to run it with [arguments] being the arguments you normally pass to the core when you start it (if any). Once the core has crashed you'll see a gdb prompt basically saying which signal caused it to stop (likely segfault). Type ```bt full``` to get a backtrace showing what code the core was executing at that point - that's what we're interested in.

<sup>(1)</sup> The alternative is getting so called "core dumps" from the crashing core, but often that requires enabling them first, making sure they're not limited in size (```ulimit -c``` may show their size is limited, basically truncating them if they get too large, which is likely the case here), and then loading them in gdb to get a backtrace. That's not going to be less fuss I think. And that's assuming you have enough free disk space to dump a (few) large core dump(s) in the first place (which could be something to consider especially on containers or VMs).

**Comment by adellaci** [comment]
@evil-at-wow 
This is what showed in terminal
'''
Loading WorldState
GameEvent 301 "Suns Reach Reclamation Phase 1" started.
GameEvent 319 "SWP - All Gates Open" started.

Playerbot: Using configuration file ../etc/playerbot.conf
---------------------------------------
      CMANGOS: World initialized       
---------------------------------------

SERVER STARTUP TIME: 0 minutes 34 seconds

[New Thread 0x7fffc617a700 (LWP 11071)]
[New Thread 0x7fffc5979700 (LWP 11072)]
[New Thread 0x7fffc5178700 (LWP 11073)]

mangos>[New Thread 0x7fffc4977700 (LWP 11074)]
[New Thread 0x7fffa3fff700 (LWP 11075)]
WorldRunnable:run Long loop #3 : 452ms (total : 1 loop(s), 33.333%)
WorldRunnable:run Long loop #4 : 100ms (total : 2 loop(s), 50.000%)
WorldRunnable:run Long loop #5 : 55ms (total : 3 loop(s), 60.000%)
WorldRunnable:run Long loop #13 : 56ms (total : 4 loop(s), 30.769%)
WorldRunnable:run Long loop #15 : 69ms (total : 5 loop(s), 33.333%)
WorldRunnable:run Long loop #69 : 106ms (total : 6 loop(s), 8.696%)
WorldRunnable:run Long loop #74 : 53ms (total : 7 loop(s), 9.459%)
WorldRunnable:run Long loop #90 : 426ms (total : 8 loop(s), 8.889%)
WorldRunnable:run Long loop #91 : 75ms (total : 9 loop(s), 9.890%)
WorldRunnable:run Long loop #99 : 56ms (total : 10 loop(s), 10.101%)
WorldRunnable:run Long loop #101 : 71ms (total : 11 loop(s), 10.891%)
WorldRunnable:run Long loop #103 : 85ms (total : 12 loop(s), 11.650%)
WorldRunnable:run Long loop #111 : 95ms (total : 13 loop(s), 11.712%)
WorldRunnable:run Long loop #113 : 62ms (total : 14 loop(s), 12.389%)
WorldRunnable:run Long loop #115 : 142ms (total : 15 loop(s), 13.043%)
WorldRunnable:run Long loop #116 : 65ms (total : 16 loop(s), 13.793%)
WorldRunnable:run Long loop #118 : 60ms (total : 17 loop(s), 14.407%)
WorldRunnable:run Long loop #120 : 50ms (total : 18 loop(s), 15.000%)
WorldRunnable:run Long loop #122 : 173ms (total : 19 loop(s), 15.574%)
WorldRunnable:run Long loop #123 : 89ms (total : 20 loop(s), 16.260%)
WorldRunnable:run Long loop #125 : 82ms (total : 21 loop(s), 16.800%)
WorldRunnable:run Long loop #127 : 58ms (total : 22 loop(s), 17.323%)
WorldRunnable:run Long loop #129 : 61ms (total : 23 loop(s), 17.829%)
WorldRunnable:run Long loop #131 : 51ms (total : 24 loop(s), 18.321%)
WorldRunnable:run Long loop #133 : 55ms (total : 25 loop(s), 18.797%)
WorldRunnable:run Long loop #135 : 57ms (total : 26 loop(s), 19.259%)
WorldRunnable:run Long loop #137 : 53ms (total : 27 loop(s), 19.708%)
WorldRunnable:run Long loop #139 : 54ms (total : 28 loop(s), 20.144%)
--Type <RET> for more, q to quit, c to continue without paging--

Thread 13 "mangosd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff4ef9700 (LWP 11069)]
0x0000555556dc183b in UnitAI::CalculateSpellRange (this=0x7fffa5b589b0, spellInfo=0x0)
    at /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.cpp:717
717	    SpellRangeEntry const* spellRange = sSpellRangeStore.LookupEntry(spellInfo->rangeIndex);

'''

**Comment by adellaci** [comment]
@evil-at-wow 
Sorry i missed the last part of your instruction. I ran again here is after 'bt full'
'''
--Type <RET> for more, q to quit, c to continue without paging--bt full

Thread 13 "mangosd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff4ef9700 (LWP 11226)]
0x0000555556dc183b in UnitAI::CalculateSpellRange (this=0x7fffac234330, spellInfo=0x0)
    at /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.cpp:717
717	    SpellRangeEntry const* spellRange = sSpellRangeStore.LookupEntry(spellInfo->rangeIndex);
(gdb) bt full
#0  0x0000555556dc183b in UnitAI::CalculateSpellRange (this=0x7fffac234330, spellInfo=0x0)
    at /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.cpp:717
        spellRange = 0x5555566991eb <SQLStorage::LookupEntry<SpellEntry>(unsigned int) const+31>
        maxRange = 4.59163468e-41
#1  0x0000555556dc3b65 in UnitAI::UpdateSpellLists (this=0x7fffac234330) at /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.cpp:1231
        spellInfo = 0x0
        maxRange = 3.0611365e-41
        spell = @0x7fffac233af8: {Id = 2141900, Position = 0, SpellId = 2, Flags = 0, CombatCondition = 1589209856, Target = 0x55555eb97328, 
          ScriptId = 0, Availability = 100, Probability = 0, InitialMin = 0, InitialMax = 0, RepeatMin = 0, RepeatMax = 0, 
          DisabledForAI = false}
        oldBehaviour = false
        result = 255
        target = 0x7ffff4ef8af0
        data = {first = 0, second = {Id = 2141900, Position = 0, SpellId = 2, Flags = 0, CombatCondition = 1589209856, 
            Target = 0x55555eb97328, ScriptId = 0, Availability = 100, Probability = 0, InitialMin = 0, InitialMax = 0, RepeatMin = 0, 
            RepeatMax = 0, DisabledForAI = false}}
        __for_range = std::map with 1 element = {[0] = {Id = 2141900, Position = 0, SpellId = 2, Flags = 0, CombatCondition = 1589209856, 
            Target = 0x55555eb97328, ScriptId = 0, Availability = 100, Probability = 0, InitialMin = 0, InitialMax = 0, RepeatMin = 0, 
            RepeatMax = 0, DisabledForAI = false}}
        __for_begin = 
    {first = 0, second = {Id = 2141900, Position = 0, SpellId = 2, Flags = 0, CombatCondition = 1589209856, Target = 0x55555eb97328, ScriptId = 0, Availability = 100, Probability = 0, InitialMin = 0, InitialMax = 0, RepeatMin = 0, RepeatMax = 0, DisabledForAI = false}}
        __for_end = 
--Type <RET> for more, q to quit, c to continue without paging--Quit
'''

**Comment by AnonXS** [comment]
There is no spell list for 2141900, strange.

**Comment by evil-at-wow** [comment]
This is starting to give useful info. Where and why it crashes is clear now:
> 0x0000555556dc183b in UnitAI::CalculateSpellRange (this=0x7fffac234330, **spellInfo=0x0**)

This is the function in the code:
```
float UnitAI::CalculateSpellRange(SpellEntry const* spellInfo) const
{
    // optimized duplicate of Spell::GetMinMaxRange for just max range
    SpellRangeEntry const* spellRange = sSpellRangeStore.LookupEntry(spellInfo->rangeIndex);
    ...
}
```
So the core is trying to calculate the range of a spell, but the spellInfo passed is a nullptr and thus using it in ```spellInfo->rangeIndex``` does boom!

We also know who's calling it that way:
> 0x0000555556dc3b65 in UnitAI::UpdateSpellLists (this=0x7fffac234330)

It's getting the spell info for SpellId 2, which is unlikely to be a valid spell indeed. And AnonXS says there is no spell list for 2141900. Without in depth checking of the tables/code I would even expect this to end with 1-99, and it suggests that it's for NPC [Infernal Attacker](https://www.wowhead.com/wotlk/npc=21419/infernal-attacker). Strange indeed, so it seems something may be off in your database for some reason (but even in the case of bogus data, we probably want to improve a few related functions so that it doesn't blow up the core). ~~Do you happen to have custom edits in your database or something like this?~~

Unfortunately we're not seeing what happens before yet because your output only lists like the top 2 frames of the stack (as hinted by the message at the bottom, there is more info).
~~Can you try this again, but press space bar a few times to get a few more pages of output please?~~
[edit] Never mind the requests, I see we're getting to the bottom of it already.

**Comment by AnonXS** [comment]
The base data for creature_template_spells were hard parsed, they included spellids like "attacking" etc that are not used in older versions or mangos, we might've missed one when we purged these for export.

e.g spell 3391
![grafik](https://github.com/cmangos/issues/assets/19734826/4d7a76d0-2cfe-4ef1-b948-0a829731bd21)

and spell 2 was not removed.

![grafik](https://github.com/cmangos/issues/assets/19734826/d2164bd1-ce91-4681-9ca6-0865a95f96f2)

**Comment by adellaci** [comment]
```
(gdb) bt full
#0  0x0000555556dc183b in UnitAI::CalculateSpellRange (this=0x7fffac234330, spellInfo=0x0)
    at /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.cpp:717
        spellRange = 0x5555566991eb <SQLStorage::LookupEntry<SpellEntry>(unsigned int) const+31>
        maxRange = 4.59163468e-41
#1  0x0000555556dc3b65 in UnitAI::UpdateSpellLists (this=0x7fffac234330) at /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.cpp:1231
        spellInfo = 0x0
        maxRange = 3.0611365e-41
        spell = @0x7fffac233af8: {Id = 2141900, Position = 0, SpellId = 2, Flags = 0, CombatCondition = 1589209856, Target = 0x55555eb97328, 
          ScriptId = 0, Availability = 100, Probability = 0, InitialMin = 0, InitialMax = 0, RepeatMin = 0, RepeatMax = 0, 
          DisabledForAI = false}
        oldBehaviour = false
        result = 255
        target = 0x7ffff4ef8af0
        data = {first = 0, second = {Id = 2141900, Position = 0, SpellId = 2, Flags = 0, CombatCondition = 1589209856, 
            Target = 0x55555eb97328, ScriptId = 0, Availability = 100, Probability = 0, InitialMin = 0, InitialMax = 0, RepeatMin = 0, 
            RepeatMax = 0, DisabledForAI = false}}
        __for_range = std::map with 1 element = {[0] = {Id = 2141900, Position = 0, SpellId = 2, Flags = 0, CombatCondition = 1589209856, 
            Target = 0x55555eb97328, ScriptId = 0, Availability = 100, Probability = 0, InitialMin = 0, InitialMax = 0, RepeatMin = 0, 
            RepeatMax = 0, DisabledForAI = false}}
        __for_begin = 
    {first = 0, second = {Id = 2141900, Position = 0, SpellId = 2, Flags = 0, CombatCondition = 1589209856, Target = 0x55555eb97328, ScriptId = 0, Availability = 100, Probability = 0, InitialMin = 0, InitialMax = 0, RepeatMin = 0, RepeatMax = 0, DisabledForAI = false}}
        __for_end = 
--Type <RET> for more, q to quit, c to continue without paging--Quit
(gdb)  
#0  0x0000555556dc183b in UnitAI::CalculateSpellRange (this=0x7fffac234330, spellInfo=0x0)
    at /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.cpp:717
        spellRange = 0x5555566991eb <SQLStorage::LookupEntry<SpellEntry>(unsigned int) const+31>
        maxRange = 4.59163468e-41
#1  0x0000555556dc3b65 in UnitAI::UpdateSpellLists (this=0x7fffac234330) at /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.cpp:1231
        spellInfo = 0x0
        maxRange = 3.0611365e-41
        spell = @0x7fffac233af8: {Id = 2141900, Position = 0, SpellId = 2, Flags = 0, CombatCondition = 1589209856, Target = 0x55555eb97328, 
          ScriptId = 0, Availability = 100, Probability = 0, InitialMin = 0, InitialMax = 0, RepeatMin = 0, RepeatMax = 0, 
          DisabledForAI = false}
        oldBehaviour = false
        result = 255
        target = 0x7ffff4ef8af0
        data = {first = 0, second = {Id = 2141900, Position = 0, SpellId = 2, Flags = 0, CombatCondition = 1589209856, 
            Target = 0x55555eb97328, ScriptId = 0, Availability = 100, Probability = 0, InitialMin = 0, InitialMax = 0, RepeatMin = 0, 
            RepeatMax = 0, DisabledForAI = false}}
        __for_range = std::map with 1 element = {[0] = {Id = 2141900, Position = 0, SpellId = 2, Flags = 0, CombatCondition = 1589209856, 
            Target = 0x55555eb97328, ScriptId = 0, Availability = 100, Probability = 0, InitialMin = 0, InitialMax = 0, RepeatMin = 0, 
            RepeatMax = 0, DisabledForAI = false}}
        __for_begin = 
    {first = 0, second = {Id = 2141900, Position = 0, SpellId = 2, Flags = 0, CombatCondition = 1589209856, Target = 0x55555eb97328, ScriptId = 0, Availability = 100, Probability = 0, InitialMin = 0, InitialMax = 0, RepeatMin = 0, RepeatMax = 0, DisabledForAI = false}}
        __for_end = 
--Type <RET> for more, q to quit, c to continue without paging--
    {first = 1, second = {Id = 0, Position = 0, SpellId = 0, Flags = 0, CombatCondition = 0, Target = 0x555557d36168 <vtable for GridReference<Creature>+16>, ScriptId = 2887974392, Availability = 32767, Probability = 2888004696, InitialMin = 32767, InitialMax = 3489225456, RepeatMin = 32767, RepeatMax = 2887976688, DisabledForAI = 255}}
        spells = @0x7fffac233370: {Id = 0, Name = "", ChanceSupportAction = 0, ChanceRangedAttack = 0, Disabled = true, 
          Spells = std::map with 1 element = {[0] = {Id = 2141900, Position = 0, SpellId = 2, Flags = 0, CombatCondition = 1589209856, 
              Target = 0x55555eb97328, ScriptId = 0, Availability = 100, Probability = 0, InitialMin = 0, InitialMax = 0, RepeatMin = 0, 
              RepeatMax = 0, DisabledForAI = false}}}
        eligibleSpells = std::vector of length 0, capacity 0
        sum = 0
        supportActionRoll = 86
        rangedActionRoll = 26
        spellRoll = 2580328991
        success = 239
#2  0x0000555556dc363d in UnitAI::UpdateAI (this=0x7fffac234330, diff=110) at /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.cpp:1145
        combat = true
        victim = 0x7fffac23cd30
#3  0x00005555568a8dcc in Unit::Update (this=0x7fffac2306f0, diff=110) at /home/mangos/cmangos/wotlk/src/game/Entities/Unit.cpp:481
No locals.
#4  0x000055555675fca2 in Creature::Update (this=0x7fffac2306f0, diff=110) at /home/mangos/cmangos/wotlk/src/game/Entities/Creature.cpp:783
No locals.
#5  0x0000555556a6491d in Map::Update (this=0x55557973e7a0, t_diff=@0x7fffa72a3c68: 110)
    at /home/mangos/cmangos/wotlk/src/game/Maps/Map.cpp:868
        wObj = 0x7fffac2306f0
--Type <RET> for more, q to quit, c to continue without paging--
        __for_range = std::unordered_set with 6432 elements = {[0] = 0x7fffa5259310, [1] = 0x7fffa5258b30, [2] = 0x7fffa5230910, [3] = 0x7fffcfd896a0, [4] = 0x7fffcfd80810, [5] = 0x7fffcfcf51a0, 
          [6] = 0x7fffcfcf9470, [7] = 0x7fffcfcec130, [8] = 0x7fffcfcf04d0, [9] = 0x7fffcfce3b60, [10] = 0x7fffcfc357b0, [11] = 0x7fffcfc243e0, [12] = 0x7fffcfc41560, [13] = 0x7fffcfc15980, 
          [14] = 0x7fffcfc16050, [15] = 0x7fffcfb87060, [16] = 0x7fffcfb7f470, [17] = 0x7fffcfa60990, [18] = 0x7fffcfb7b3d0, [19] = 0x7fffcf912290, [20] = 0x7fffcf7fc000, [21] = 0x7fffcf7ff8a0, 
          [22] = 0x7fffcf7f68f0, [23] = 0x7fffcf7f7000, [24] = 0x7fffcf7f77a0, [25] = 0x7fffcf7f7f40, [26] = 0x7fffcf7aff20, [27] = 0x7fffa5235f90, [28] = 0x7fffa52350e0, [29] = 0x7fffcf6cc9f0, 
          [30] = 0x7fffcf676770, [31] = 0x7fffcf679f30, [32] = 0x7fffcf1cffa0, [33] = 0x7fffcf1bd710, [34] = 0x7fffcf1c10b0, [35] = 0x7fffcf1c54d0, [36] = 0x7fffcf1c8d40, [37] = 0x7fffcf1cc5b0, 
          [38] = 0x7fff9482f1e0, [39] = 0x7fff94832be0, [40] = 0x7fff9483d920, [41] = 0x7fff94811e90, [42] = 0x7fff94822ec0, [43] = 0x7fff94808810, [44] = 0x7fff948079e0, [45] = 0x7fffcf1936c0, 
          [46] = 0x7fffcf185850, [47] = 0x7fffcf184870, [48] = 0x7fffcf17fad0, [49] = 0x7fff947d9570, [50] = 0x7fff947dda30, [51] = 0x7fff947d5a90, [52] = 0x7fffcf14db30, [53] = 0x7fffcf1527f0, 
          [54] = 0x7fffcf148ca0, [55] = 0x7fffcf144700, [56] = 0x7fffcf132aa0, [57] = 0x7fffcf136f60, [58] = 0x7fffcf13b420, [59] = 0x7fff947b2f60, [60] = 0x7fff947aea90, [61] = 0x7fff9479e840, 
          [62] = 0x7fff9479df30, [63] = 0x7fff947956f0, [64] = 0x7fff94799b10, [65] = 0x7fffcf116350, [66] = 0x7fffcf108e10, [67] = 0x7fffcf1085b0, [68] = 0x7fffcf106e50, [69] = 0x7fffcf1075f0, 
          [70] = 0x7fff94774400, [71] = 0x7fff94778080, [72] = 0x7fff947705e0, [73] = 0x7fff94767cf0, [74] = 0x7fff9474ea90, [75] = 0x7fff94756d10, [76] = 0x7fff9475b010, [77] = 0x7fff9475f430, 
          [78] = 0x7fff9473d990, [79] = 0x7fff94741db0, [80] = 0x7fffcf0f12d0, [81] = 0x7fff947148a0, [82] = 0x7fff947182a0, [83] = 0x7fff9471c6c0, [84] = 0x7fff94720ae0, [85] = 0x7fff946ff210, 
          [86] = 0x7fffcf09c100, [87] = 0x7fffcf0ae420, [88] = 0x7fffcf0b1df0, [89] = 0x7fffcf0b57c0, [90] = 0x7fffcf0b9190, [91] = 0x7fffcf0bcb60, [92] = 0x7fffcf0c0530, [93] = 0x7fffcf0c3f00, 
          [94] = 0x7fffcf0cb2a0, [95] = 0x7fffcf097330, [96] = 0x7fffcf07a4b0, [97] = 0x7fffcf07de80, [98] = 0x7fffcf081850, [99] = 0x7fffcf085220, [100] = 0x7fffcf08ff90, [101] = 0x7fffcf093960, 
          [102] = 0x7fffcf038280, [103] = 0x7fffcf0433b0, [104] = 0x7fffcf046bf0, [105] = 0x7fffcf058530, [106] = 0x7fffcf0044f0, [107] = 0x7fffcf007fe0, [108] = 0x7fffcf00baf0, [109] = 0x7fffcf00f600, 
          [110] = 0x7fffcf01ae10, [111] = 0x7fffcf021f80, [112] = 0x7fffcf0257c0, [113] = 0x7fffcf030e80, [114] = 0x7fff946d59a0, [115] = 0x7fff946d1350, [116] = 0x7fff946c1bf0, [117] = 0x7fff946c5f40, 
          [118] = 0x7fff946cd350, [119] = 0x7fff946bddd0, [120] = 0x7fff94679940, [121] = 0x7fff946ad120, [122] = 0x7fff946b4e70, [123] = 0x7fffcefa2f80, [124] = 0x7fffcefaf140, [125] = 0x7fffcefb2b70, 
          [126] = 0x7fffcefb69e0, [127] = 0x7fffcefba3b0, [128] = 0x7fffcefbdd80, [129] = 0x7fffcefc8af0, [130] = 0x7fffcefcfe90, [131] = 0x7fffcef9d980, [132] = 0x7fffcef89580, [133] = 0x7fffcef8d090, 
          [134] = 0x7fffcef912d0, [135] = 0x7fffcef94a80, [136] = 0x7fffcef73020, [137] = 0x7fffcef76860, [138] = 0x7fffcef7a0a0, [139] = 0x7fffcef7d8e0, [140] = 0x7fffcef81b20, [141] = 0x7fff946962b0, 
          [142] = 0x7fff94685b50, [143] = 0x7fff94664cc0, [144] = 0x7fffcfd85320, [145] = 0x7fffcf173450, [146] = 0x7fffce54c210, [147] = 0x7fffce550f10, [148] = 0x7fffce55a690, [149] = 0x7fffce55f220, 
          [150] = 0x7fffce5635f0, [151] = 0x7fffce567ab0, [152] = 0x7fffce4ea270, [153] = 0x7fffce5278f0, [154] = 0x7fffce52bbb0, [155] = 0x7fffce53a100, [156] = 0x7fffce53ec90, [157] = 0x7fffce543060, 
          [158] = 0x7fffce547520, [159] = 0x7fffce4cea60, [160] = 0x7fffce4d81e0, [161] = 0x7fffce4dcd70, [162] = 0x7fffce4e1140, [163] = 0x7fffce4c9540, [164] = 0x7fffce49be80, [165] = 0x7fffce4ae560, 
          [166] = 0x7fffce4b2a20, [167] = 0x7fffce4b7690, [168] = 0x7fffce4bc260, [169] = 0x7fffcebeaa90, [170] = 0x7fffcebef620, [171] = 0x7fffcebf39f0, [172] = 0x7fffcebbd270, [173] = 0x7fffcebc1650, 
          [174] = 0x7fffcebc61e0, [175] = 0x7fffcebd3d90, [176] = 0x7fffceba5ec0, [177] = 0x7fffcebaaa50, [178] = 0x7fffcebaee20, [179] = 0x7fffcebb3a30, [180] = 0x7fffceb9fc00, [181] = 0x7fffceba09a0, 
          [182] = 0x7fffceb9bd10, [183] = 0x7fffceb4ac40, [184] = 0x7fffceb46c80, [185] = 0x7fffceb3e0b0, [186] = 0x7fffceb42490, [187] = 0x7fffceb2fe40, [188] = 0x7fffceb22080, [189] = 0x7fffceb2ab10, 
          [190] = 0x7fffceb0ba10, [191] = 0x7fffceb0fc30, [192] = 0x7fffceb133b0, [193] = 0x7fffceb0b280, [194] = 0x7fffceb00260, [195] = 0x7fffceb07340, [196] = 0x7fffceaf4bf0, [197] = 0x7fffceaeb9d0, 
          [198] = 0x7fffceae3590, [199] = 0x7fffceae7690...}
        __for_begin = {<std::__detail::_Node_iterator_base<WorldObject*, false>> = {_M_cur = 0x7fff9c048250}, <No data fields>}
        __for_end = {<std::__detail::_Node_iterator_base<WorldObject*, false>> = {_M_cur = 0x0}, <No data fields>}
        count = 5788
        objToUpdate = std::unordered_set with 6432 elements = {[0] = 0x7fffa5259310, [1] = 0x7fffa5258b30, [2] = 0x7fffa5230910, [3] = 0x7fffcfd896a0, [4] = 0x7fffcfd80810, [5] = 0x7fffcfcf51a0, 
          [6] = 0x7fffcfcf9470, [7] = 0x7fffcfcec130, [8] = 0x7fffcfcf04d0, [9] = 0x7fffcfce3b60, [10] = 0x7fffcfc357b0, [11] = 0x7fffcfc243e0, [12] = 0x7fffcfc41560, [13] = 0x7fffcfc15980, 
          [14] = 0x7fffcfc16050, [15] = 0x7fffcfb87060, [16] = 0x7fffcfb7f470, [17] = 0x7fffcfa60990, [18] = 0x7fffcfb7b3d0, [19] = 0x7fffcf912290, [20] = 0x7fffcf7fc000, [21] = 0x7fffcf7ff8a0, 
          [22] = 0x7fffcf7f68f0, [23] = 0x7fffcf7f7000, [24] = 0x7fffcf7f77a0, [25] = 0x7fffcf7f7f40, [26] = 0x7fffcf7aff20, [27] = 0x7fffa5235f90, [28] = 0x7fffa52350e0, [29] = 0x7fffcf6cc9f0, 
          [30] = 0x7fffcf676770, [31] = 0x7fffcf679f30, [32] = 0x7fffcf1cffa0, [33] = 0x7fffcf1bd710, [34] = 0x7fffcf1c10b0, [35] = 0x7fffcf1c54d0, [36] = 0x7fffcf1c8d40, [37] = 0x7fffcf1cc5b0, 
          [38] = 0x7fff9482f1e0, [39] = 0x7fff94832be0, [40] = 0x7fff9483d920, [41] = 0x7fff94811e90, [42] = 0x7fff94822ec0, [43] = 0x7fff94808810, [44] = 0x7fff948079e0, [45] = 0x7fffcf1936c0, 
          [46] = 0x7fffcf185850, [47] = 0x7fffcf184870, [48] = 0x7fffcf17fad0, [49] = 0x7fff947d9570, [50] = 0x7fff947dda30, [51] = 0x7fff947d5a90, [52] = 0x7fffcf14db30, [53] = 0x7fffcf1527f0, 
          [54] = 0x7fffcf148ca0, [55] = 0x7fffcf144700, [56] = 0x7fffcf132aa0, [57] = 0x7fffcf136f60, [58] = 0x7fffcf13b420, [59] = 0x7fff947b2f60, [60] = 0x7fff947aea90, [61] = 0x7fff9479e840, 
          [62] = 0x7fff9479df30, [63] = 0x7fff947956f0, [64] = 0x7fff94799b10, [65] = 0x7fffcf116350, [66] = 0x7fffcf108e10, [67] = 0x7fffcf1085b0, [68] = 0x7fffcf106e50, [69] = 0x7fffcf1075f0, 
          [70] = 0x7fff94774400, [71] = 0x7fff94778080, [72] = 0x7fff947705e0, [73] = 0x7fff94767cf0, [74] = 0x7fff9474ea90, [75] = 0x7fff94756d10, [76] = 0x7fff9475b010, [77] = 0x7fff9475f430, 
          [78] = 0x7fff9473d990, [79] = 0x7fff94741db0, [80] = 0x7fffcf0f12d0, [81] = 0x7fff947148a0, [82] = 0x7fff947182a0, [83] = 0x7fff9471c6c0, [84] = 0x7fff94720ae0, [85] = 0x7fff946ff210, 
          [86] = 0x7fffcf09c100, [87] = 0x7fffcf0ae420, [88] = 0x7fffcf0b1df0, [89] = 0x7fffcf0b57c0, [90] = 0x7fffcf0b9190, [91] = 0x7fffcf0bcb60, [92] = 0x7fffcf0c0530, [93] = 0x7fffcf0c3f00, 
          [94] = 0x7fffcf0cb2a0, [95] = 0x7fffcf097330, [96] = 0x7fffcf07a4b0, [97] = 0x7fffcf07de80, [98] = 0x7fffcf081850, [99] = 0x7fffcf085220, [100] = 0x7fffcf08ff90, [101] = 0x7fffcf093960, 
          [102] = 0x7fffcf038280, [103] = 0x7fffcf0433b0, [104] = 0x7fffcf046bf0, [105] = 0x7fffcf058530, [106] = 0x7fffcf0044f0, [107] = 0x7fffcf007fe0, [108] = 0x7fffcf00baf0, [109] = 0x7fffcf00f600, 
          [110] = 0x7fffcf01ae10, [111] = 0x7fffcf021f80, [112] = 0x7fffcf0257c0, [113] = 0x7fffcf030e80, [114] = 0x7fff946d59a0, [115] = 0x7fff946d1350, [116] = 0x7fff946c1bf0, [117] = 0x7fff946c5f40, 
          [118] = 0x7fff946cd350, [119] = 0x7fff946bddd0, [120] = 0x7fff94679940, [121] = 0x7fff946ad120, [122] = 0x7fff946b4e70, [123] = 0x7fffcefa2f80, [124] = 0x7fffcefaf140, [125] = 0x7fffcefb2b70, 
          [126] = 0x7fffcefb69e0, [127] = 0x7fffcefba3b0, [128] = 0x7fffcefbdd80, [129] = 0x7fffcefc8af0, [130] = 0x7fffcefcfe90, [131] = 0x7fffcef9d980, [132] = 0x7fffcef89580, [133] = 0x7fffcef8d090, 
          [134] = 0x7fffcef912d0, [135] = 0x7fffcef94a80, [136] = 0x7fffcef73020, [137] = 0x7fffcef76860, [138] = 0x7fffcef7a0a0, [139] = 0x7fffcef7d8e0, [140] = 0x7fffcef81b20, [141] = 0x7fff946962b0, 
          [142] = 0x7fff94685b50, [143] = 0x7fff94664cc0, [144] = 0x7fffcfd85320, [145] = 0x7fffcf173450, [146] = 0x7fffce54c210, [147] = 0x7fffce550f10, [148] = 0x7fffce55a690, [149] = 0x7fffce55f220, 
          [150] = 0x7fffce5635f0, [151] = 0x7fffce567ab0, [152] = 0x7fffce4ea270, [153] = 0x7fffce5278f0, [154] = 0x7fffce52bbb0, [155] = 0x7fffce53a100, [156] = 0x7fffce53ec90, [157] = 0x7fffce543060, 
          [158] = 0x7fffce547520, [159] = 0x7fffce4cea60, [160] = 0x7fffce4d81e0, [161] = 0x7fffce4dcd70, [162] = 0x7fffce4e1140, [163] = 0x7fffce4c9540, [164] = 0x7fffce49be80, [165] = 0x7fffce4ae560, 
          [166] = 0x7fffce4b2a20, [167] = 0x7fffce4b7690, [168] = 0x7fffce4bc260, [169] = 0x7fffcebeaa90, [170] = 0x7fffcebef620, [171] = 0x7fffcebf39f0, [172] = 0x7fffcebbd270, [173] = 0x7fffcebc1650, 
          [174] = 0x7fffcebc61e0, [175] = 0x7fffcebd3d90, [176] = 0x7fffceba5ec0, [177] = 0x7fffcebaaa50, [178] = 0x7fffcebaee20, [179] = 0x7fffcebb3a30, [180] = 0x7fffceb9fc00, [181] = 0x7fffceba09a0, 
          [182] = 0x7fffceb9bd10, [183] = 0x7fffceb4ac40, [184] = 0x7fffceb46c80, [185] = 0x7fffceb3e0b0, [186] = 0x7fffceb42490, [187] = 0x7fffceb2fe40, [188] = 0x7fffceb22080, [189] = 0x7fffceb2ab10, 
--Type <RET> for more, q to quit, c to continue without paging--
          [190] = 0x7fffceb0ba10, [191] = 0x7fffceb0fc30, [192] = 0x7fffceb133b0, [193] = 0x7fffceb0b280, [194] = 0x7fffceb00260, [195] = 0x7fffceb07340, [196] = 0x7fffceaf4bf0, [197] = 0x7fffceaeb9d0, 
          [198] = 0x7fffceae3590, [199] = 0x7fffceae7690...}
        obj_updater = {m_objectToUpdateSet = std::unordered_set with 6432 elements = {[0] = 0x7fffa5259310, [1] = 0x7fffa5258b30, [2] = 0x7fffa5230910, [3] = 0x7fffcfd896a0, [4] = 0x7fffcfd80810, 
            [5] = 0x7fffcfcf51a0, [6] = 0x7fffcfcf9470, [7] = 0x7fffcfcec130, [8] = 0x7fffcfcf04d0, [9] = 0x7fffcfce3b60, [10] = 0x7fffcfc357b0, [11] = 0x7fffcfc243e0, [12] = 0x7fffcfc41560, 
            [13] = 0x7fffcfc15980, [14] = 0x7fffcfc16050, [15] = 0x7fffcfb87060, [16] = 0x7fffcfb7f470, [17] = 0x7fffcfa60990, [18] = 0x7fffcfb7b3d0, [19] = 0x7fffcf912290, [20] = 0x7fffcf7fc000, 
            [21] = 0x7fffcf7ff8a0, [22] = 0x7fffcf7f68f0, [23] = 0x7fffcf7f7000, [24] = 0x7fffcf7f77a0, [25] = 0x7fffcf7f7f40, [26] = 0x7fffcf7aff20, [27] = 0x7fffa5235f90, [28] = 0x7fffa52350e0, 
            [29] = 0x7fffcf6cc9f0, [30] = 0x7fffcf676770, [31] = 0x7fffcf679f30, [32] = 0x7fffcf1cffa0, [33] = 0x7fffcf1bd710, [34] = 0x7fffcf1c10b0, [35] = 0x7fffcf1c54d0, [36] = 0x7fffcf1c8d40, 
            [37] = 0x7fffcf1cc5b0, [38] = 0x7fff9482f1e0, [39] = 0x7fff94832be0, [40] = 0x7fff9483d920, [41] = 0x7fff94811e90, [42] = 0x7fff94822ec0, [43] = 0x7fff94808810, [44] = 0x7fff948079e0, 
            [45] = 0x7fffcf1936c0, [46] = 0x7fffcf185850, [47] = 0x7fffcf184870, [48] = 0x7fffcf17fad0, [49] = 0x7fff947d9570, [50] = 0x7fff947dda30, [51] = 0x7fff947d5a90, [52] = 0x7fffcf14db30, 
            [53] = 0x7fffcf1527f0, [54] = 0x7fffcf148ca0, [55] = 0x7fffcf144700, [56] = 0x7fffcf132aa0, [57] = 0x7fffcf136f60, [58] = 0x7fffcf13b420, [59] = 0x7fff947b2f60, [60] = 0x7fff947aea90, 
            [61] = 0x7fff9479e840, [62] = 0x7fff9479df30, [63] = 0x7fff947956f0, [64] = 0x7fff94799b10, [65] = 0x7fffcf116350, [66] = 0x7fffcf108e10, [67] = 0x7fffcf1085b0, [68] = 0x7fffcf106e50, 
            [69] = 0x7fffcf1075f0, [70] = 0x7fff94774400, [71] = 0x7fff94778080, [72] = 0x7fff947705e0, [73] = 0x7fff94767cf0, [74] = 0x7fff9474ea90, [75] = 0x7fff94756d10, [76] = 0x7fff9475b010, 
            [77] = 0x7fff9475f430, [78] = 0x7fff9473d990, [79] = 0x7fff94741db0, [80] = 0x7fffcf0f12d0, [81] = 0x7fff947148a0, [82] = 0x7fff947182a0, [83] = 0x7fff9471c6c0, [84] = 0x7fff94720ae0, 
            [85] = 0x7fff946ff210, [86] = 0x7fffcf09c100, [87] = 0x7fffcf0ae420, [88] = 0x7fffcf0b1df0, [89] = 0x7fffcf0b57c0, [90] = 0x7fffcf0b9190, [91] = 0x7fffcf0bcb60, [92] = 0x7fffcf0c0530, 
            [93] = 0x7fffcf0c3f00, [94] = 0x7fffcf0cb2a0, [95] = 0x7fffcf097330, [96] = 0x7fffcf07a4b0, [97] = 0x7fffcf07de80, [98] = 0x7fffcf081850, [99] = 0x7fffcf085220, [100] = 0x7fffcf08ff90, 
            [101] = 0x7fffcf093960, [102] = 0x7fffcf038280, [103] = 0x7fffcf0433b0, [104] = 0x7fffcf046bf0, [105] = 0x7fffcf058530, [106] = 0x7fffcf0044f0, [107] = 0x7fffcf007fe0, 
            [108] = 0x7fffcf00baf0, [109] = 0x7fffcf00f600, [110] = 0x7fffcf01ae10, [111] = 0x7fffcf021f80, [112] = 0x7fffcf0257c0, [113] = 0x7fffcf030e80, [114] = 0x7fff946d59a0, 
            [115] = 0x7fff946d1350, [116] = 0x7fff946c1bf0, [117] = 0x7fff946c5f40, [118] = 0x7fff946cd350, [119] = 0x7fff946bddd0, [120] = 0x7fff94679940, [121] = 0x7fff946ad120, 
            [122] = 0x7fff946b4e70, [123] = 0x7fffcefa2f80, [124] = 0x7fffcefaf140, [125] = 0x7fffcefb2b70, [126] = 0x7fffcefb69e0, [127] = 0x7fffcefba3b0, [128] = 0x7fffcefbdd80, 
            [129] = 0x7fffcefc8af0, [130] = 0x7fffcefcfe90, [131] = 0x7fffcef9d980, [132] = 0x7fffcef89580, [133] = 0x7fffcef8d090, [134] = 0x7fffcef912d0, [135] = 0x7fffcef94a80, 
            [136] = 0x7fffcef73020, [137] = 0x7fffcef76860, [138] = 0x7fffcef7a0a0, [139] = 0x7fffcef7d8e0, [140] = 0x7fffcef81b20, [141] = 0x7fff946962b0, [142] = 0x7fff94685b50, 
            [143] = 0x7fff94664cc0, [144] = 0x7fffcfd85320, [145] = 0x7fffcf173450, [146] = 0x7fffce54c210, [147] = 0x7fffce550f10, [148] = 0x7fffce55a690, [149] = 0x7fffce55f220, 
            [150] = 0x7fffce5635f0, [151] = 0x7fffce567ab0, [152] = 0x7fffce4ea270, [153] = 0x7fffce5278f0, [154] = 0x7fffce52bbb0, [155] = 0x7fffce53a100, [156] = 0x7fffce53ec90, 
            [157] = 0x7fffce543060, [158] = 0x7fffce547520, [159] = 0x7fffce4cea60, [160] = 0x7fffce4d81e0, [161] = 0x7fffce4dcd70, [162] = 0x7fffce4e1140, [163] = 0x7fffce4c9540, 
            [164] = 0x7fffce49be80, [165] = 0x7fffce4ae560, [166] = 0x7fffce4b2a20, [167] = 0x7fffce4b7690, [168] = 0x7fffce4bc260, [169] = 0x7fffcebeaa90, [170] = 0x7fffcebef620, 
            [171] = 0x7fffcebf39f0, [172] = 0x7fffcebbd270, [173] = 0x7fffcebc1650, [174] = 0x7fffcebc61e0, [175] = 0x7fffcebd3d90, [176] = 0x7fffceba5ec0, [177] = 0x7fffcebaaa50, 
            [178] = 0x7fffcebaee20, [179] = 0x7fffcebb3a30, [180] = 0x7fffceb9fc00, [181] = 0x7fffceba09a0, [182] = 0x7fffceb9bd10, [183] = 0x7fffceb4ac40, [184] = 0x7fffceb46c80, 
            [185] = 0x7fffceb3e0b0, [186] = 0x7fffceb42490, [187] = 0x7fffceb2fe40, [188] = 0x7fffceb22080, [189] = 0x7fffceb2ab10, [190] = 0x7fffceb0ba10, [191] = 0x7fffceb0fc30, 
            [192] = 0x7fffceb133b0, [193] = 0x7fffceb0b280, [194] = 0x7fffceb00260, [195] = 0x7fffceb07340, [196] = 0x7fffceaf4bf0, [197] = 0x7fffceaeb9d0, [198] = 0x7fffceae3590, 
            [199] = 0x7fffceae7690...}, m_timeDiff = 110}
        grid_object_update = {i_visitor = @0x7ffff4ef8d10}
        world_object_update = {i_visitor = @0x7ffff4ef8d10}
        __PRETTY_FUNCTION__ = "virtual void Map::Update(const uint32&)"
        __FUNCTION__ = <optimized out>
#6  0x0000555556a9488e in MapUpdateWorker::execute (this=0x7fffa72a3c50) at /home/mangos/cmangos/wotlk/src/game/Maps/MapWorkers.h:52
No locals.
#7  0x0000555556aabde9 in MapUpdater::WorkerThread (this=0x5555614de3c8) at /home/mangos/cmangos/wotlk/src/game/Maps/MapUpdater.cpp:96
        request = 0x7fffa72a3c50
#8  0x0000555556aae7da in std::__invoke_impl<void, void (MapUpdater::*)(), MapUpdater*> (__f=@0x555579615050: (void (MapUpdater::*)(MapUpdater * const)) 0x555556aabd68 <MapUpdater::WorkerThread()>, 
    __t=@0x555579615048: 0x5555614de3c8) at /usr/include/c++/9/bits/invoke.h:73
No locals.
#9  0x0000555556aae708 in std::__invoke<void (MapUpdater::*)(), MapUpdater*> (__fn=@0x555579615050: (void (MapUpdater::*)(MapUpdater * const)) 0x555556aabd68 <MapUpdater::WorkerThread()>)
    at /usr/include/c++/9/bits/invoke.h:95
No locals.
#10 0x0000555556aae667 in std::thread::_Invoker<std::tuple<void (MapUpdater::*)(), MapUpdater*> >::_M_invoke<0ul, 1ul> (this=0x555579615048) at /usr/include/c++/9/thread:244
No locals.
#11 0x0000555556aae61e in std::thread::_Invoker<std::tuple<void (MapUpdater::*)(), MapUpdater*> >::operator() (this=0x555579615048) at /usr/include/c++/9/thread:251
No locals.
#12 0x0000555556aae5fe in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (MapUpdater::*)(), MapUpdater*> > >::_M_run (this=0x555579615040) at /usr/include/c++/9/thread:195
No locals.
#13 0x00007ffff7466de4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#14 0x00007ffff7f9f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
--Type <RET> for more, q to quit, c to continue without paging--
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737302730496, -3812058699483014086, 140737488346094, 140737488346095, 140737488346096, 140737302728576, 3812069555587554362, 3812076343399717946}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#15 0x00007ffff7151133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
(gdb) 
```
[debug_data.txt](https://github.com/cmangos/issues/files/11644569/debug_data.txt)

**Comment by AnonXS** [comment]
apply last db update and try again, if the 2 spellid has to stay we can use the pr that was submitted to mangos.tbc^

but yea if it's only crashing in wotlk maybe wotlk misses some update. spell 2 just also exists in tbc.

```
-- https://github.com/cmangos/mangos-tbc/pull/613
-- https://github.com/cmangos/issues/issues/3416#issuecomment-1575278870
UPDATE creature_template_spells SET spell1 = 0 WHERE spell1 = 2; -- 574
UPDATE creature_template_spells SET spell2 = 0 WHERE spell2 = 2; -- 0
UPDATE creature_template_spells SET spell3 = 0 WHERE spell3 = 2; -- 0
UPDATE creature_template_spells SET spell4 = 0 WHERE spell4 = 2; -- 0
UPDATE creature_template_spells SET spell5 = 0 WHERE spell5 = 2; -- 0
UPDATE creature_template_spells SET spell6 = 0 WHERE spell6 = 2; -- 0
UPDATE creature_template_spells SET spell7 = 0 WHERE spell7 = 2; -- 0
UPDATE creature_template_spells SET spell8 = 0 WHERE spell8 = 2; -- 0
UPDATE creature_template_spells SET spell9 = 0 WHERE spell9 = 2; -- 0
UPDATE creature_template_spells SET spell10 = 0 WHERE spell10 = 2; -- 0

DELETE FROM `creature_template_spells` WHERE `spell1` = 0 AND `spell2` = 0 AND `spell3` = 0 AND `spell4` = 0 AND `spell5` = 0 AND `spell6` = 0 AND `spell7` = 0 AND `spell8` = 0 AND `spell9` = 0 AND `spell10` = 0; -- 56


```

**Comment by adellaci** [comment]
@evil-at-wow 
I checked the database 'spell1' is the only one that has '2' in it. I created an update query.

```
UPDATE creature_template_spells SET spell1 = 0 WHERE spell1 = 2;
```
Loaded it, started the server and it has remained up.

**Comment by AnonXS** [comment]
Has been resolved.

**Comment by adellaci** [comment]
@AnonXS  it does not appear to be fix in WoTLK
WoTLK Core 0ab920a701aa2b82952ef1c34dc722637f785709
Database 638e33c23d922c7acd32b3a90a8a245b5edd1a1d
Still have this issue..tested this morning. I had to rerun my sql query so the server would not crash

**Comment by AnonXS** [comment]
When https://github.com/cmangos/mangos-tbc/commit/117a4ea6124c46bf4e320108a9643de58804fdd8 is ported.

**Comment by adellaci** [comment]
@AnonXS Thank you
and
@evil-at-wow Thank you for your help
