### ISSUE TITLE
🐛 [Bug Report] [WOTLK] Ability cooldown (shield wall)

### ISSUE THREAD

**Issue by Mige5** [cmangos/issues#3418]
### Bug Details

Im pretty sure this was working fine, but this time I somehow managed to click it while logging in so it was moving the ability from the actionbar and then I just clicked it back to its place, and the cooldown showed this:

EDIT: This actually seems to happen everytime.

![image](https://github.com/cmangos/issues/assets/24878041/3be52820-b0cb-4e1f-b3d4-8014d8ff460d)

### Steps to Reproduce
EDIT: 
1. Use the ability (it will show normal cooldown, however it wont work after that as the actual cooldown is 12h)
2. Logout
3. Login (now will show 12h)

### Expected behavior

Should have normal cooldown.

### Core SHA1 Commit Hash

*

### Database SHA1 Commit Hash

*

### Operating System

Win10

### Client Version

4.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
This is usually a visual client-side bug. Relogging or reloading should fix it

**Comment by Mige5** [comment]
> This is usually a visual client-side bug. Relogging or reloading should fix it

Well not this time, tried relogging before and didnt fix. and had the server off for a while, and now started it to go and check, and it still on 10h cooldown.

**Comment by Mige5** [comment]
Added steps to reproduce.
