### ISSUE TITLE
🐛 [Bug Report] WotLK - When using food does not show reduced count/stack size in bag or shortcut bar.

### ISSUE THREAD

**Issue by kelbren** [cmangos/issues#3970]
### Bug Details

When eating or drinking the stack size  of the item in your bag does not show a  decrease. 
Closing your bag and opening it again shows  the correct amount.
If the item is in a shortcut bar slot, it does not reflect a change even when the item in your bag does, unless the item stack is consumed completely then the shortcut bar shows 0.

### Steps to Reproduce

1. by a stack of cheese.
2.  open bag, and eat some
3.  count does not change, until bag is closed and re-opened
4.  place stack on shortcut bar, eat, no change.

### Expected behavior

counts should change when used.

### Core SHA1 Commit Hash

.

### Database SHA1 Commit Hash

.

### Operating System

Ubuntu 24.04

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by Kashemir001** [comment]
Can confirm the same issue on Windows 10. It also happens with flasks, bandages, bombs and consumables for abilities. Core revision used cmangos/mangos-wotlk@72df39075

**Comment by virusav** [comment]
The problem may be in the method (or its call)
```
void Player::DestroyItemCount(Item* pItem, uint32& count, bool update)
```

If you comment out the lines
```
        if (IsInWorld() && update)
            GetMap()->AddUpdateCreateObject(pItem);
```
or replace **pItem** with **this**, then everything will work.

In all calls to this method, the **update** parameter is always equal to **true**.
If you pass the **update** parameter equal to **false** when calling from the **void Spell::TakeCastItem()** method, everything also works.

This is just a debugging step, not a fix, as you need to check all calls to the specified method with different objects to make sure nothing breaks anywhere.

**Comment by Kashemir001** [comment]
I've traced this bug to be introduced in cmangos/mangos-wotlk@d7b6125f2

**Comment by killerwife** [comment]
I pushed a commit to wotlk core that should address this issue. I dont have the facilities to test it rn. Please let me know if it helped.

**Comment by virusav** [comment]
Stackable food and drink work.

**Comment by Kashemir001** [comment]
The problem persists for consumables for abilities, e.g. light feathers for slow fall/levitate, holy candles for prayer of fortitude.

**Comment by kelbren** [comment]
Confirmed: food/drink works. reagents do not reflect the count unless close and open bag.

**Comment by killerwife** [comment]
Second case solved check pls

**Comment by kelbren** [comment]
Did a quick test with my paladin and reagent shows correct counts now, so reagents and food working.

**Comment by Kashemir001** [comment]
Yep, everything seems to work now. I've tested food, reagents, bandages, elixirs and bombs. Thanks!

I'd like to note that now item count number displayed on action bar / in bags is often updated with a small, but noticeable delay, something about 200-400ms I'd say by feel. I'm comparing to a build of cmangos/mangos-wotlk@9662ecfa9 (just before the bug was introduced), in which item count update is consistantly really snappy. Of course it may be a general server lag (although there were only a few long loops messages in console) or some other codebase changes since then.

The following `Player::DestroyItemCount()` refactor broke playerbots module compilation, but that is out of current scope :p

Also, there is a related bug (I guess, first appears in the same commit as this one) when combining two stacks of an item so that the resulting stack would overflow max size. If you try to do so, both origin stacks get "locked" (greyed out in bags and can't be interacted with) until you relog. But I guess it is worth opening a separate issue.
