### ISSUE TITLE
[Cata] Build Fail at 0%

### ISSUE THREAD

**Issue by Talmeron** [cmangos/issues#795]
I tried gcc/++ 4.7, 4.8, and 4.9.

[  0%] Building CXX object CMakeFiles/genrev.dir/src/tools/genrevision/genrevision.cpp.o
/home/exaurdon/mangos/src/tools/genrevision/genrevision.cpp: In function ‘void extractDataFromGit(FILE*, std::string, bool, RawData&)’:
/home/exaurdon/mangos/src/tools/genrevision/genrevision.cpp:86:26: error: ‘nullptr’ was not declared in this scope
         char* host_str = nullptr;
                          ^
CMakeFiles/genrev.dir/build.make:54: recipe for target 'CMakeFiles/genrev.dir/src/tools/genrevision/genrevision.cpp.o' failed
make[2]: *** [CMakeFiles/genrev.dir/src/tools/genrevision/genrevision.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/genrev.dir/all' failed
make[1]: *** [CMakeFiles/genrev.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Talmeron** [comment]
Ubuntu 14.04

**Comment by xfurry** [comment]
Poke @evil-at-wow, @cyberium  and @DasBlub 

Sorry, but I have no idea how to fix this, as I don't user cmake.

**Comment by evil-at-wow** [comment]
It looks like cmangos/mangos-wotlk@434d1334 wasn't merged, because the CMake files are missing all the common and C++11 stuff in this branch. As a result, GCC and clang won't build in C++11 mode, which is required for things like nullptr.

I fixed that with cmangos/mangos-cata@771cd948, but I don't think this fixes the entire build yet, becaues there is still cmangos/issues#786.

**Comment by BeerfishWoW** [comment]
@evil-at-wow I'm still getting the following error when trying to install the fresh WotLK version of CMaNGOS:
mangos@SNOWFALL:~/Build$ make
Scanning dependencies of target genrev
[  0%] Building CXX object CMakeFiles/genrev.dir/src/tools/genrevision/genrevision.cpp.o
Linking CXX executable genrev
[  0%] Built target genrev
Scanning dependencies of target revision.h
make[2]: *** [CMakeFiles/revision.h] Segmentation fault (core dumped)
make[1]: *** [CMakeFiles/revision.h.dir/all] Error 2
make: *** [all] Error 2

Do I have to wait until a fix has been found in cmangos/issues#786?
